config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users, :sessions, :pages, :password_resets

  resources :families, concerns: :paginatable do
    get   'approval_letter' => 'families#approval_letter'
    post  'approval_letter' => 'families#approval_letter'
    collection { get :search }
    resources :updates
    resources :donations
    resources :grants
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'dashboard' => 'pages#dashboard'
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'contact' => 'pages#contact'
  get 'unsub' => 'pages#unsub'

  get 'donate' => 'donations#new'
  resources :charity do
    resources :donations
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'thanks' => 'donations#thanks'

  namespace :admin do
    get '/' => 'pages#dashboard'
    resources :users
    resources :donations
    resources :grants do
      get 'deny_grant' => 'grants#grant_denied'
    end
    resources :families do
      collection { get :search }
      resources :donations
      resources :updates
      resources :grants
      get 'toggle_approval', on: :member
      get 'toggle_visibility', on: :member
    end
    resources :charities
    resources :pages
  end

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'oauths/oauth'
  get 'oauths/callback'

  match '/:slug' => 'pages#show', via: [:get, :post]

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/pages/_body_instructions.html.haml
%span.small.help-block
  This is the actual page content. It is what will show on the entire page. You can use HTML<!-- or Markdown (choose which you prefer below)-->, but first some things to remember:
  %ul
    %li #{link_to 'Bootstrap v3.3.6', 'http://getbootstrap.com/', target: '_blank'} & the #{link_to 'custom theme', 'https://github.com/carterdea/adopttogether/tree/master/app/assets/stylesheets/application', target: '_blank'} cascade before your custom styles
    %li If you need to use Javascript look up #{link_to 'how to use JS with Turbolinks', 'http://guides.rubyonrails.org/working_with_javascript_in_rails.html#how-turbolinks-works', target: '_blank'} (tl;dr #{link_to "this will not work: $(document).on('ready', function () { /* ... */ });", 'https://github.com/kossnocorp/jquery.turbolinks#user-content-not-working-with-documentonready', target: '_blank'})
    %li Images need to be hosted on our AWS S3 bucket, ask Carter for the credentials
  Here are the HTML tags you can use:
  %code &lt;div&gt;
  ,
  %code &lt;p&gt;
  ,
  %code &lt;a&gt;
  ,
  %code &lt;img&gt;
  ,
  %code &lt;form&gt;
  ,
  %code &lt;label&gt;
  ,
  %code &lt;input&gt;
  ,
  %code &lt;textarea&gt;
  ,
  %code &lt;select&gt;
  ,
  %code &lt;option&gt;
  ,
  %code &lt;button&gt;
  ,
  %code &lt;span&gt;
  ,
  %code &lt;script&gt;
  ,
  %code &lt;style&gt;
  ,
  %code &lt;iframe&gt;
  ,
  %code &lt;embed&gt;
  ,
  %code &lt;blockquote&gt;
  ,
  %code &lt;strong&gt;
  ,
  %code &lt;em&gt;
  ,
  %code &lt;u&gt;
  ,
  %code &lt;span&gt;
  ,
  %code &lt;hr&gt;
  ,
  %code &lt;br&gt;
  ,
  %code &lt;ul&gt;
  ,
  %code &lt;ol&gt;
  ,
  %code &lt;li&gt;
  ,
  %code &lt;table&gt;
  ,
  %code &lt;tr&gt;
  ,
  %code &lt;th&gt;
  ,
  %code &lt;td&gt;

app/views/admin/pages/_form.html.haml
= form_for [:admin, @page] do |f|
  = render 'shared/errors', object: page
  .row
    .col-xs-12.col-md-6
      .form-group
        = f.label :title
        = f.text_field :title, size: 40, autofocus: true, class: 'form-control', 'data-parsley-trigger' => 'focusout change', required: :true
        %span.small.help-block This is the internal title, end users won't see this
      .form-group
        = f.label :slug
        .input-group
          %span.input-group-addon http://www.adopttogether.org/
          = f.text_field :slug, size: 40, class: 'form-control', 'data-parsely-trigger' => 'focusout change', required: :true
        %span.small.help-block
          This is the URL. Needs to be in this format:
          %code example-page
  .form-group
    = f.label :body
    = f.text_area :body, size: '40x20', class: 'form-control'
    #editor
    = render 'body_instructions'
  .row
    .col-xs-12.col-md-6
      .form-group
        = f.label :seo_title
        = f.text_field :seo_title, size: 40, class: 'form-control'
        %span.small.help-block This is the title shown in the top of the browser & on Google, it should be optimized for SEO.
  .form-group
    = f.label :seo_description
    = f.text_field :seo_description, size: 40, class: 'form-control'
    %span.small.help-block This is the paragraph of text shown under the title in the Google search result, it should be optimized for SEO.
  .btn-group{'data-toggle' => 'buttons'}
    = f.label :live_true, class: 'btn btn-default' do
      = f.radio_button :live, :true
      Live
    = f.label :live_false, class: 'btn btn-default' do
      = f.radio_button :live, :false
      Hidden
  = f.hidden_field :created_by, value: @current_user.email
  .row
    .col-xs-12.col-md-6.col-lg-4
      = f.submit class: 'btn btn-primary btn-block'

app/views/admin/pages/dashboard.html.haml
.row
  .col-xs-12.col-md-4
    %ul.nav.nav-pills.nav-stacked
      %li= nav_link_to 'Families', admin_families_path
      %li= nav_link_to 'Donations', admin_donations_path
      %li= nav_link_to 'Grants', admin_grants_path
      %li= nav_link_to 'Users', admin_users_path
      %li= nav_link_to 'Pages', admin_pages_path
  .col-xs-12.col-md-8
    %h1 Admin Dashboard
    %p #{pretty_dollars(global_donations)} Total Donations
    %p Lots of stuff is going to go here. Have a suggestion for what I should put here? Email me: me at carterdea dot com

app/views/admin/pages/edit.html.haml
%h1 
  %span.small.show
    = link_to 'Pages', admin_pages_path
    \ /
  Edit #{@page.title}
= render 'form', page: @page

app/views/admin/pages/index.html.haml
= link_to 'Create a Page', new_admin_page_path, class: 'btn btn-primary pull-right'
%h1
  %span.small.show
    = link_to 'Admin', admin_path
    \ /
    - if @page
      = link_to @page.name, :back
  All #{pluralize(@pages.total_count, 'Page')}
= paginate(@pages)
%table.table.table-hover
  %thead
    %tr
      %th= sortable 'title', 'Title'
      %th= sortable 'slug', 'URL'
      %th= sortable 'created_by', 'Created By'
      %th= sortable 'created_at', 'Created At'
      %th= sortable 'updated_at', 'Updated At'
      %th= sortable 'Status', 'Status'
  %tbody
    - @pages.each do |page|
      %tr
        %td= page.title
        %td= link_to page.slug, root_url + page.slug
        %td= page.created_by
        %td.small{title: page.created_at.strftime("on %-m/%-d/%Y at %l:%M %p")} #{time_ago_in_words(page.created_at)} ago
        %td.small{title: page.updated_at.strftime("on %-m/%-d/%Y at %l:%M %p")} #{time_ago_in_words(page.updated_at)} ago
        %td
          = link_to '📝', edit_admin_page_path(page), title: 'Edit Page'

app/views/admin/pages/new.html.haml
%h1 
  %span.small.show
    = link_to 'Pages', admin_pages_path
    \ /
  Create a Page
= render 'form', page: @page