config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users, :sessions, :pages, :password_resets

  resources :families, concerns: :paginatable do
    get   'approval_letter' => 'families#approval_letter'
    post  'approval_letter' => 'families#approval_letter'
    collection { get :search }
    resources :updates
    resources :donations
    resources :grants
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'dashboard' => 'pages#dashboard'
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'contact' => 'pages#contact'
  get 'unsub' => 'pages#unsub'

  get 'donate' => 'donations#new'
  resources :charity do
    resources :donations
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'thanks' => 'donations#thanks'

  namespace :admin do
    get '/' => 'pages#dashboard'
    resources :users
    resources :donations
    resources :grants do
      get 'deny_grant' => 'grants#grant_denied'
    end
    resources :families do
      collection { get :search }
      resources :donations
      resources :updates
      resources :grants
      get 'toggle_approval', on: :member
      get 'toggle_visibility', on: :member
    end
    resources :charities
    resources :pages
  end

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'oauths/oauth'
  get 'oauths/callback'

  match '/:slug' => 'pages#show', via: [:get, :post]

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id                   :integer          not null, primary key
#  user_id              :integer
#  first_name           :string
#  last_name            :string
#  phone                :string
#  postal_code          :string
#  city                 :string
#  state                :string
#  cost                 :decimal(15, 2)   default(0.0)
#  country              :string
#  gender               :string
#  quantity             :integer
#  description          :text
#  status               :string
#  agency_name          :string
#  agency_site          :string
#  photo                :string
#  approved             :boolean          default(TRUE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  approval_letter_file :string
#  slug                 :string
#  address              :string
#  visible              :boolean          default(TRUE)
#  donations_count      :integer          default(0)
#  updates_count        :integer          default(0)
#  grants_count         :integer          default(0)
#

require 'elasticsearch/model'
require 'file_size_validator'

# app/models/family.rb
class Family < ActiveRecord::Base  
  VALID_URL_REGEX = %r{\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z}
  ADOPTION_STATUSES = [
    'Paperwork Not Started',
    'Paperwork Filed',
    'Homestudy Scheduled',
    'Homestudy Completed',
    'Awaiting Matching',
    'Matched',
    'Completed'
  ]

  belongs_to :user, touch: true, dependent: :destroy
  has_many :donations, as: :recipient, dependent: :destroy
  has_many :updates, dependent: :destroy
  has_many :grants, dependent: :destroy

  validates :first_name, :last_name, :postal_code, :user_cost, :cost, presence: true
  validates :photo, presence: true, file_size: { maximum: 2.megabytes.to_i }
  validates_length_of :description, maximum: 2000, message: 'Please keep your story to less than 2,000 characters.'
  validates :cost, numericality: { less_than: 1_000_000 }
  validates :country, presence: true, length: { is: 2 }
  validates :quantity, numericality: { greater_than: 0 }
  validates :slug, uniqueness: true, presence: true, exclusion: { in: EXCLUDED_SLUGS }
  validates :phone, :address, :city, :state, presence: true, on: :update
  validates :agency_site, format: VALID_URL_REGEX, allow_blank: true
  validates_associated :user, on: :create

  before_validation :generate_slug, on: :create
  before_validation :add_http

  mount_uploader :photo, ImageUploader
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  scope :approved, -> { where(approved: true).order('families.created_at DESC') }
  scope :unapproved, -> { where approved: false }

  scope :visible, -> { where(visible: true).order('families.created_at DESC') }
  scope :hidden, -> { where(visible: false) }

  scope :include_total_raised, -> { joins('LEFT OUTER JOIN donations ON families.id = donations.recipient_id').select('families.*, COALESCE(SUM(donations.amount), 0) AS total_raised').group('families.id') }

  def to_param
    slug
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  # Using a virtual attribute (user cost for cost) to clean up the user input
  def user_cost
    cost if cost
  end

  def user_cost=(cost)
    self.cost = cost.delete('$,') if cost.present?
  end

  def funded?
  end

  def country_name
    Country["#{country}"].name
  end

  def pluralize_is
    if first_name.include?(' ' || 'and' || '&')
      'are'
    else
      'is'
    end
  end

  def number_of_children
    if quantity > 1
      "#{quantity} children"
    else
      'a child'
    end
  end

  def total_amount_donated_until(date)
    donations.where('date(created_at) <= ?', date).sum(:amount)
  end

  def donations_chart_data(start = 1.weeks.ago)
    (start.to_date.prev_day..Date.tomorrow).map do |date|
      {
        date: date.to_s,
        amount: total_amount_donated_until(date)
      }
    end
  end

  def self.to_csv(options = { headers: true })
    CSV.generate(options) do |csv|
      attributes = %w(id user_id first_name last_name quantity country status total_raised cost status approved visible phone address city state postal_code agency_name slug donations_count updates_count grants_count created_at updated_at)
      csv << attributes
      all.include_total_raised.each do |family|
        csv << attributes.map { |attr| family.send(attr) }
      end
    end
  end

  private

  def generate_slug
    self.slug ||= "the-#{last_name.pluralize.parameterize}"
    suffix = 1
    while Family.find_by_slug(self.slug)
      self.slug = "the-#{last_name.pluralize.parameterize}-#{suffix}"
      suffix += 1
    end
  end

  def add_http
    if agency_site.present?
      self.agency_site = "http://#{agency_site}" unless agency_site[%r{\Ahttp:\/\/}] || agency_site[%r{\Ahttps:\/\/}]
    end
  end
end

Family.__elasticsearch__.create_index! force: true
Family.import
Family.__elasticsearch__.refresh_index!

app/controllers/admin/families_controller.rb
class Admin::FamiliesController < ADMIN::AdminController
  before_filter :set_family, only: [:toggle_approval, :toggle_visibility]

  load_and_authorize_resource

  def index
    @families = Family.include_total_raised.includes(:user).order(sort_column + ' ' + sort_direction).page(params[:page]).per(30)
    respond_to do |format|
      format.html
      format.csv { send_data Family.to_csv, filename: "families-#{Date.today}.csv" }
      format.xls { send_data Family.to_csv(col_sep: "\t"), filename: "families-#{Date.today}.xls" }
    end
  end

  def search
    if params[:q].present?
      @families = Family.approved.visible.search(params[:q]).records.include_total_raised.page(params[:page]).per(30)
      render :index
    else
      redirect_to admin_families_path
    end
  end

  def toggle_approval
    @family.toggle!(:approved)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def toggle_visibility
    @family.toggle!(:visible)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def set_family
    if params[:id]
      @family = Family.include_total_raised.find_by_slug!(params[:id])
    elsif params[:family_id]
      @family = Family.include_total_raised.find_by_slug!(params[:family_id])
    end
  end

  def family_params
    params.require(:family).permit(:first_name, :last_name, :phone, :address, :city, :state, :postal_code, :user_cost, :country, :gender, :quantity, :description, :status, :agency_name, :agency_site, :photo, :approval_letter_file, :slug)
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:edit, :show, :update, :approval_letter]

  load_and_authorize_resource
  before_action :require_login, only: [:edit, :update, :destroy, :approval_letter]

  def index
    @families = Family.approved.visible.include_total_raised.select(:id, :photo, :first_name, :last_name, :country, :slug).order('families.created_at DESC').page(params[:page]).per(30)
  end

  def search
    if params[:q].present?
      @families = Family.approved.visible.search(params[:q]).records.include_total_raised.page(params[:page]).per(30)
      render :index
    else
      redirect_to families_path
    end
  end

  def show
    @donations = @family.donations.order('id DESC').page(params[:page]).per(10)
    @updates = @family.updates.order('created_at DESC').page(params[:page]).per(5)
  end

  def new
    @user = User.new unless current_user
    @family = Family.new
  end

  def create
    if current_user
      @user = current_user
      @family = @user.build_family(family_params)
      if @family.save
        FamilyMailer.new_family_email(@family).deliver_later
        redirect_to @family, notice: 'Your family profile is now live! Share it with friends to start raising funds for your adoption.'
      else
        flash.now[:alert] = 'There was a problem with your family profile. Please check it and try again.'
        render :new
      end
    else
      @user = User.new(user_params)
      @family = @user.build_family(family_params)
      if @user.valid? && @family.valid?
        @user.save unless current_user
        @family.save
        login(user_params[:email], user_params[:password])
        FamilyMailer.new_family_email(@family).deliver_later
        redirect_to family_path(@family), notice: 'Your family profile is now live! Share it with friends to start raising funds for your adoption.'
      else
        flash.now[:alert] = 'There was a problem with your family profile. Please check it and try again.'
        render :new
      end
    end
  end

  def edit
  end

  def approval_letter
  end

  def update
    if @family.update(family_params)
      if Rails.application.routes.recognize_path(request.referer)[:action] == 'approval_letter' ## If the user is coming to Families#Update from 'Approval Letter', send them back to Grants#Update
        redirect_to family_grants_path(@family), notice: 'Thanks for uploading your approval letter! We\'ll take a look at it and get back to you soon.'
      else
        redirect_to @family, notice: 'Your family profile has been updated.'
      end
    else
      render :edit
    end
  end

  def destroy
    @family.destroy
    redirect_to root_url, alert: 'Your family profile has successfully been deleted. We\'re sorry to see you go.'
  end

  private

  def set_family
    if params[:id]
      @family = Family.include_total_raised.find_by_slug!(params[:id])
    elsif params[:family_id]
      @family = Family.include_total_raised.find_by_slug!(params[:family_id])
    end
  end

  def family_params
    params.require(:family).permit(:first_name, :last_name, :phone, :address, :city, :state, :postal_code, :user_cost, :country, :gender, :quantity, :description, :status, :agency_name, :agency_site, :photo, :approval_letter_file, :slug)
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  def formatted_cost(family)
    '$' + number_with_delimiter(family.cost)
  end
end

app/views/families/_blank_slate.html.haml
%p.small.help-block.text-center There are no families fundraising 😕

app/views/families/_family_index_thumbs.html.haml
.col-xs-6.col-md-4
  = yield

app/views/families/_form.html.haml
= form_for family, html: { multipart: true, 'data-parsley-validate' => true } do |f|
  = render 'shared/errors', object: family
  %fieldset
    %legend Family Information
    .row
      .col-xs-12.col-sm-8.col-md-8.col-lg-6
        .form-group
          = f.label :first_name, 'First Name(s)'
          = f.text_field :first_name, autofocus: true, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
        .form-group
          = f.label :last_name, 'Last Name'
          = f.text_field :last_name, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
        - if family.persisted?
          .form-group
            = f.label :address
            = f.text_field :address, class: 'form-control', autocorrect: 'off'
          .form-group
            = f.label :city
            = f.text_field :city, class: 'form-control'
          .form-group
            = f.label :state
            = f.select :state, options_for_select(us_states, family.state), { include_blank: true }, class: 'form-control'
        .form-group
          = f.label :postal_code, 'Zip/Postal Code'
          = f.text_field :postal_code, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
        - if family.persisted?
          .form-group
            = f.label :phone
            = f.text_field :phone, class: 'form-control'
  - if current_user == nil
    %fieldset
      .row
        .col-xs-12.col-sm-8.col-md-8.col-lg-6
          %legend Login Information
          = fields_for :user do |ff|
            .form-group
              = ff.label :email
              = ff.email_field :email, class: 'form-control', type: :email, 'data-parsley-trigger' => 'focusout change', required: :true
            .form-group
              = ff.label :password
              = ff.password_field :password, class: 'form-control', required: :true, minlength: 6, 'data-parsley-trigger' => 'focusout change'
              %p.help-block.small Must be at least 6 characters. You'll use this email & password to log back in.
  %fieldset
    %legend Adoption Information
    .row
      .col-xs-12.col-sm-8.col-md-8.col-lg-6
        .form-group
          = f.label :user_cost, 'Estimated Adoption Cost'
          .input-group
            %span.input-group-addon $
            = f.text_field :user_cost, value: number_with_precision(family.cost, precision: 0) || 0, class: 'form-control'
        .form-group
          = f.label :country
          = f.country_select :country, { priority_countries: ['US'] }, { class: 'form-control' }
        .form-group
          = f.label :quantity, 'How many children are you adopting?'
          = f.select :quantity, options_for_select(1..5), { }, { class: 'form-control' }
      .col-xs-12
        .form-group
          = f.label :description, 'Message to your visitors'
          = f.text_area :description, size: '40x9', class: 'form-control', required: :true, maxlength: 2000, 'data-parsley-trigger' => 'focusout change'
          %p.help-block.small Keep this brief, simple and to the point. You can edit this at any time.
      .col-xs-12.col-sm-8.col-md-8.col-lg-6
        .form-group
          = f.label :photo
          = f.file_field :photo, accept: 'image/png,image/gif,image/jpeg,image/jpg'
        .form-group
          = f.label :status, 'Adoption Status'
          = f.select :status, options_for_select(Family::ADOPTION_STATUSES), {}, { class: 'form-control' }
        .form-group
          = f.label :agency_name, 'Adoption Agency'
          = f.text_field :agency_name, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
        .form-group
          = f.label :agency_site do
            Adoption Agency URL
            %span.optional (Optional)
          .input-group
            %span.input-group-addon http://
            = f.text_field :agency_site, class: 'form-control', 'data-parsely-pattern' => '\b((?=[a-z0-9-]{1,63}\.)(xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,63}\b', 'data-parsley-trigger' => 'focusout change'
  - if family.persisted?
    %fieldset
      %legend Profile Information
      .row
        .col-xs-12.col-sm-8.col-md-8.col-lg-6
          .form-group
            = f.label :slug, 'AdoptTogether URL'
            .input-group
              %span.input-group-addon http://adopttogether.org/
              = f.text_field :slug, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
  .row
    .col-xs-12.col-sm-8.col-md-8.col-lg-6
      = f.submit class: 'btn btn-primary btn-block', data: { disable_with: 'Creating Your Family Profile...' }

app/views/families/approval_letter.html.haml
.row
  .col-xs-12.col-sm-8
    %h1 Upload Your Approval Letter
    %p You need to upload a copy of your HomeStudy or a Letter of Acceptance from your Adoption agency for the AdoptTogether staff to review. Once approved, your fundraising profile will become live and ready to receive support from generous donors.
    = form_for @family, html: { multipart: true } do |f|
      %fieldset
        %legend Family Information
        .row
          .col-xs-12.col-sm-8.col-md-8.col-lg-6
            .form-group
              = f.label :address
              = f.text_field :address, required: true, class: 'form-control'
            .form-group
              = f.label :city
              = f.text_field :city, required: true, class: 'form-control'
            .form-group
              = f.label :state
              = f.select :state, options_for_select(us_states), {}, required: true, class: 'form-control'
            .form-group
              = f.label :phone
              = f.text_field :phone, required: true, class: 'form-control'
          .col-xs-12
            .form-group
              = f.label :approval_letter_file, 'Approval Letter'
              = f.file_field(:approval_letter_file, accept: 'image/png,image/gif,image/jpeg,image/jpg')
              %p.small.help-block You can upload a Word document, PDF, JPEG, PNG or ZIP. If you want to upload multiple files, zip them and upload the ZIP file.
          .col-xs-12.col-sm-8.col-md-8.col-lg-6
            = f.submit 'Upload Your Approval Letter', class: 'btn btn-primary btn-block'
  %aside.col-xs-12.col-sm-4
    %h2 Details here
    %p Gimme some text. Maybe this is a list of things we approve, why we need this, etc.

app/views/families/edit.html.haml
.row
  .col-xs-12.col-sm-4
    = render 'shared/dashboard_nav', family: @family
  .col-xs-12.col-sm-8
    %h1 Edit Your Family Profile
    %p Here you can edit or update your family profile. It's best to keep your profile up to date with new photos, updated adoption status, etc.
    = render 'form', family: @family

app/views/families/index.html.haml
- if params[:q].blank?
  %h1 All Families
  %h2= pluralize(Family.all.count, 'Adopting family')
- else
  %h1 Search Results for "#{params[:q]}"
  %h2= pluralize(@families.length, 'Adopting family') # Using length instead of count to keep the join intact
.row
  = render partial: 'shared/family_thumb', collection: @families, as: :family, layout: 'family_index_thumbs' || 'We can\'t find any families :('
= paginate @families

app/views/families/new.html.haml
.row
  .col-xs-12.col-sm-8
    %h1 Start a Family Profile
    %p Hey! We are so excited to help you fundraise for your adoption. Please take a few minutes to fill out the information below and we’ll get you started.
    = render 'form', family: @family
    / .lock
    /   = image_tag('lock.png', height: 23, alt: 'Secured by Stripe')
    /   %p Your information is secure with 256 bit SSL encryption
  %aside.col-xs-12.col-sm-4
    %h2 FAQ
    %h4 What do I need to start raising money on AdoptTogether?
    %p Just give us a family photo, adoption agency, etc and then when you request your first grant we'll need a letter of approval from your agency or adoption lawyer in order to send you the first grant.
    %h4 How long does it take to get a grant awarded?
    %p Grants are usually approved and sent within 2 weeks. You can expect to receieve it within 2-3 weeks.
    %h4 Can I donate to my own account?
    %p No, AdoptTogether does not allow families to donate to their own account.
    %h4 How long can we keep our profile up?
    %p You can keep the profile up as long as you have costs associated to the adoption. For some families it's 6 mos, 1 year, for some families it's longer.

app/views/families/show.html.haml
.row
  - cache(@family) do
    .col-xs-12.col-sm-8
      .family-details
        = image_tag(@family.photo.large.url, alt: "#{@family.full_name} is raising money on AdoptTogether for their adoption from #{@family.country_name}.", class: 'img-responsive')
        %h1.title= @family.full_name
        %h2.subtitle #{@family.pluralize_is} adopting #{@family.number_of_children} from #{@family.country_name}
        .description= simple_format(@family.description)
        .row
          .col-xs-6
            %h4 Adoption Status
            %h3= @family.status
          .col-xs-6.agency
            %h4 Adoption Agency
            %h3= @family.agency_name
            %span.website= link_to @family.agency_site, @family.agency_site, target: '_blank'
        .row
          .col-xs-12
            %h2 Updates
            - cache(['updates_list', @updates.map(&:id), @updates.maximum(:updated_at)]) do
              %ul.list-unstyled.update-list
                = render partial: 'shared/update', collection: @updates, as: :update, locals: {family: @family} || 'This family has not posted any updates yet.'
                = paginate @updates

  %aside.col-xs-12.col-sm-4
    .raised
      - cache(@family.total_raised) do
        %h3 Raised
        %span.total-raised= pretty_dollars(@family.total_raised)
        %span.goal of #{pretty_dollars(@family.cost)} Goal
      - if current_user && @family == current_user.family
        %span.btn.btn-primary.btn-lg.btn-block.disabled Give to this Adoption
        %span.help-block.small Unfortunately, the IRS won't let you give to your own Adoption. Sorry about that! 😩
      - else
        = link_to 'Give to this Adoption', new_family_donation_path(@family), class: 'btn btn-primary btn-lg btn-block'
    .share-buttons
      %span.share-count= share_count(family_url(@family))
      %span.shares Shares
      = render 'shared/share_buttons', family: @family
    - cache(['donations_list', @donations.map(&:id), @donations.maximum(:updated_at)]) do
      %h2= pluralize(@donations.total_count, 'Donation')
      %ul.list-unstyled
        - cache(["donation_list", @donations.map(&:id), @donations.maximum(:updated_at)]) do
          = render partial: 'shared/donation', collection: @donations, as: :donation || 'No one has donated to this family. You can be the first!'
          = paginate @donations