config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users, :sessions, :pages, :password_resets

  resources :families, concerns: :paginatable do
    get   'approval_letter' => 'families#approval_letter'
    post  'approval_letter' => 'families#approval_letter'
    collection { get :search }
    resources :updates
    resources :donations
    resources :grants
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'dashboard' => 'pages#dashboard'
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'contact' => 'pages#contact'
  get 'unsub' => 'pages#unsub'

  get 'donate' => 'donations#new'
  resources :charity do
    resources :donations
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'thanks' => 'donations#thanks'

  namespace :admin do
    get '/' => 'pages#dashboard'
    resources :users
    resources :donations
    resources :grants do
      get 'deny_grant' => 'grants#grant_denied'
    end
    resources :families do
      collection { get :search }
      resources :donations
      resources :updates
      resources :grants
      get 'toggle_approval', on: :member
      get 'toggle_visibility', on: :member
    end
    resources :charities
    resources :pages
  end

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'oauths/oauth'
  get 'oauths/callback'

  match '/:slug' => 'pages#show', via: [:get, :post]

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_app_js.html.haml
:javascript
  // set stripe key
  Stripe.setPublishableKey('#{Rails.configuration.stripe[:publishable_key]}');

  // heap
  window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var n=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(n?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(a,o);for(var r=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=r(p[c])};
  heap.load("2036506896");

  // google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  // more google analytics
  ga('create', 'UA-28151708-1', 'auto');

app/views/shared/_dashboard_nav.html.haml
%ul.nav.nav-pills.nav-stacked
  %li= nav_link_to 'Dashboard', dashboard_path
  - if family.present?
    %li= nav_link_to 'Your Updates', family_updates_path(family), {}, {:controller_segment => 1}
    %li= nav_link_to 'Edit Family Profile', edit_family_path(family)
    %li= nav_link_to 'Your Grants', family_grants_path(family), {}, {:controller_segment => 1}
  -# %li= nav_link_to 'My Fundraisers', "#"

app/views/shared/_donation.html.haml
%li.donor
  %h5= donation.donor_name
  %span.amount
    gave #{donation.donation_amount}
    - if donation.message?
      and said:
  - if donation.message?
    %blockquote "#{donation.message}"

app/views/shared/_errors.html.haml
- if object.errors.any?
  .errors
    %h3 Oops! The #{object.class.name.titleize.downcase} could not be saved.
    %ul
      - object.errors.full_messages.each do |error|
        %li= error

app/views/shared/_family_thumb.html.haml
.family
  = link_to (image_thumb(family, "img-responsive")), family
  .caption
    %h3= link_to family.full_name, family
    %span.location #{family.pluralize_is} adopting from #{family.country_name}
    %span.raised #{pretty_dollars(family.total_raised)} Raised 

app/views/shared/_robots.html.haml
%meta(name='robots' content=visibility)

app/views/shared/_share_buttons.html.haml
- title = url_encode("#{family.full_name} on AdoptTogether")
- text_intro = url_encode("The #{family.last_name} Family is raising money for their adoption on ")
- url = url_encode(family_url(family))
- text_prompt = url_encode("Check it out!")
- image = url_encode(image_url(family.photo.large.url))
.row
  .col-xs-6.share-button
    = link_to "Facebook", "https://www.facebook.com/sharer/sharer.php?u=#{url}", class: 'facebook'
  .col-xs-6.share-button
    = link_to 'Twitter', "https://twitter.com/home?status=#{text_intro}%40Adoptt,%20#{text_prompt}%20#{url}", class: 'twitter'
.row
  .col-xs-6.share-button
    = link_to 'Google +', "https://plus.google.com/share?url=#{url}", class: 'google-plus'
  .col-xs-6.share-button
    = link_to 'LinkedIn', "https://www.linkedin.com/shareArticle?mini=true&url=#{url}&title=#{title}&summary=#{text_intro}AdoptTogether.#{text_prompt}&source=", class: 'linkedin'
.row
  .col-xs-6.share-button
    = link_to 'Pinterest', "https://pinterest.com/pin/create/button/?url=#{url}&media=#{image}&description=#{text_intro}AdoptTogether.%20#{text_prompt}}", class: 'pinterest'
  .col-xs-6.share-button
    =link_to 'Email', "mailto:?&subject=#{title}&body=#{text_intro}AdoptTogether.%20#{text_prompt}%20#{url}%0A%0AThanks!", class: 'email'
= text_field_tag :url, family_url(family), class: "form-control", onClick: "this.setSelectionRange(0, this.value.length)"

app/views/shared/_update.html.haml
%li.update
  %h4 Update #{update.sequential_id}
  - if update.video_url?
    .video-responsive
      = video_embed(update.video_url)
  = image_tag(update.photo.large.url, class: 'img-responsive') if update.photo?
  %h3= update.title
  %span.date= update.date_created
  .body
    = simple_format(update.message)
  - if current_user && current_user.family == update.family
    .actions
      = link_to('Edit', edit_family_update_path(family, update), class: 'btn btn-default btn-sm')
      = link_to('Delete', family_update_path(family, update), method: :delete, class: 'btn btn-danger btn-sm', 'data-confirm' => 'Are you sure you want to delete this Update? You can\'t undo this.')