config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users, :sessions, :pages, :password_resets

  resources :families, concerns: :paginatable do
    get   'approval_letter' => 'families#approval_letter'
    post  'approval_letter' => 'families#approval_letter'
    collection { get :search }
    resources :updates
    resources :donations
    resources :grants
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'dashboard' => 'pages#dashboard'
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'contact' => 'pages#contact'
  get 'unsub' => 'pages#unsub'

  get 'donate' => 'donations#new'
  resources :charity do
    resources :donations
    match 'donations/cancel/:token' => 'donations#cancel_monthly_donation', via: :get
  end

  get 'thanks' => 'donations#thanks'

  namespace :admin do
    get '/' => 'pages#dashboard'
    resources :users
    resources :donations
    resources :grants do
      get 'deny_grant' => 'grants#grant_denied'
    end
    resources :families do
      collection { get :search }
      resources :donations
      resources :updates
      resources :grants
      get 'toggle_approval', on: :member
      get 'toggle_visibility', on: :member
    end
    resources :charities
    resources :pages
  end

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'oauths/oauth'
  get 'oauths/callback'

  match '/:slug' => 'pages#show', via: [:get, :post]

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/donation.rb
# == Schema Information
#
# Table name: donations
#
#  id                   :integer          not null, primary key
#  amount               :decimal(15, 2)   default(0.0)
#  recurring            :boolean
#  at_tip               :integer          default(0)
#  family_email_updates :string           default("t")
#  message              :text
#  name                 :string
#  email                :string
#  at_newsletter        :boolean
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  hide_amount          :boolean
#  anonymous            :boolean
#  stripe_id            :string
#  token                :string
#  recipient_id         :integer
#  recipient_type       :string
#

class Donation < ActiveRecord::Base
  DONATION_AMOUNTS = [
    30, 50, 100, 500, 1000
  ]

  TIP_AMOUNTS = [
    [0, 'None'], [10, '10%'], [20, '20%']
  ]

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  attr_accessor :stripe_token, :stripe_customer_id

  belongs_to :recipient, polymorphic: true, counter_cache: true, touch: true

  delegate :full_name, to: :recipient

  validates :name, presence: true
  validates :email, presence: true, format: VALID_EMAIL_REGEX
  validates :amount, numericality: { greater_than_or_equal_to: 1, message: 'Must be at least $1.' }
  validates :at_tip, numericality: true, allow_nil: true

  has_secure_token
  require 'stripe'

  def donor_name
    if anonymous
      'Anonymous'
    else
      name
    end
  end

  def donation_amount
    if hide_amount
      'an undisclosed amount'
    else
      '$' + (amount.to_i).to_s
    end
  end

  def tip_total
    at_tip
  end

  def total_amount_in_dollars
    (amount + tip_total).to_i
  end

  def total_amount_in_cents
    (amount + tip_total).to_i * 100
  end

  def type
    if recurring
      'Monthly Donation'
    else
      'One-Time Donation'
    end
  end

  def stripe_charge_description
    "#{name}'s donation to #{full_name}"
  end

  def stripe_customer_description
    "#{name}'s (#{email}) monthly donation to #{full_name}"
  end

  def self.average_donation_amount
    Rails.cache.fetch('average_donation_amount', expires_in: 12.hours) do
      if Donation.any?
        Donation.average(:amount)
      else
        0
      end
    end
  end

  # Single Donations

  def create_stripe_charge
    if valid?
      # Create the charge on Stripe's servers - this will charge the user's card
      begin
        charge = Stripe::Charge.create(
          amount: total_amount_in_cents, # amount in cents, again
          currency: 'usd',
          source: stripe_token,
          description: stripe_charge_description,
          receipt_email: email
        )
      rescue Stripe::CardError => e
        # The card has been declined
      end
    end
  end

  # Customers

  def charge_stripe_customer
    Stripe::Charge.create(
      amount: total_amount_in_cents, # in cents
      currency: 'usd',
      customer: stripe_id
    )
  end

  def delete_stripe_customer
    customer = Stripe::Customer.retrieve(self.stripe_id)
    customer.delete
  end

  # Subscriptions (Stripe Recurring)

  def subscribe_stripe_customer
    if valid?
      customer = Stripe::Customer.create(
        source: stripe_token,
        plan: 'monthly-gift-test', # this is a monthly plan w/ 1¢
        email: email,
        quantity: total_amount_in_cents,
        description: stripe_customer_description
      )
      save_customer_id(customer)
    end
  end

  def save_customer_id(customer)
    self.stripe_id = customer.id
  end

  def self.to_csv(options = { headers: true })
    CSV.generate(options) do |csv|
      attributes = %w(id amount recurring at_tip recipient_id recipient_type message name email anonymous hide_amount  stripe_id recipient_id recipient_type created_at updated_at)
      csv << attributes
      all.each do |family|
        csv << attributes.map { |attr| family.send(attr) }
      end
    end
  end
end

app/controllers/admin/donations_controller.rb
class Admin::DonationsController < ADMIN::AdminController
  load_and_authorize_resource

  def index
    if params[:family_id]
      @family = Family.find_by_slug!(params[:family_id])
      @donations = @family.donations.all.order(sort_column + ' ' + sort_direction).page(params[:page]).per(30)
    else
      @donations = Donation.all.includes(:recipient).order(sort_column + ' ' + sort_direction).page(params[:page]).per(30)
      respond_to do |format|
        format.html
        format.csv { send_data Donation.to_csv, filename: "donations-#{Date.today}.csv" }
        format.xls { send_data Donation.to_csv(col_sep: "\t"), filename: "donations-#{Date.today}.xls" }
      end
    end
  end

  def edit
    @donation = Donation.find(params[:id])
    @recipient = @donation.recipient
  end

  def update
  end
end

app/controllers/donations_controller.rb
# app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_recipient, except: [:thanks, :cancel_monthly_donation, :delete, :destroy]

  def show
  end

  def index
  end

  def new
    @donation = @recipient.donations.new
  end

  def create
    @donation = @recipient.donations.build(donation_params)
    @stripe_token = :stripe_token
    if @donation.recurring
      if @donation.subscribe_stripe_customer && @donation.save
        DonationMailer.monthly_donation_receipt(@donation).deliver_later
        DonationMailer.donation_received(@donation).deliver_later unless @donation.recipient_type == 'Charity'
        set_session_ids
        redirect_to :thanks
      else
        render :new
      end
    else
      if @donation.create_stripe_charge && @donation.save
        DonationMailer.donation_receipt(@donation).deliver_later
        DonationMailer.donation_received(@donation).deliver_later unless @donation.recipient_type == 'Charity'
        set_session_ids
        redirect_to :thanks
      else
        render :new
      end
    end
  end

  def thanks
    @donation = Donation.find(session[:donation_id])
    if session[:recipient_type] == 'Family'
      @recipient = Family.include_total_raised.find(session[:recipient_id])
    elsif session[:recipient_type] == 'Charity'
      @recipient = Charity.find(session[:recipient_id])
    end
  end

  def edit
    @donation = @recipient.donations.find(params[:id])
  end

  def update
    @donation = @recipient.donations.find(params[:id])
    if @donation.update(donation_params)
      unless @donation.recurring
        @donation.delete_stripe_customer
        DonationMailer.cancel_monthly_donation_confirmation(@donation).deliver_later
      end
      redirect_to root_url, notice: 'Your donation has been canceled.'
    else
      render :edit
    end
  end

  def delete
  end

  def destroy
  end

  def cancel_monthly_donation
    @donation = Donation.find_by(token: params[:token])
    @recipient = @donation.recipient
  end

  private

  def set_recipient
    if params[:family_id].present?
      @recipient = Family.include_total_raised.find_by_slug!(params[:family_id])
    else
      @recipient = Charity.find(1)
    end
  end

  def set_session_ids
    session[:donation_id] = @donation.id
    session[:recipient_type] = @donation.recipient_type
    session[:recipient_id] = @donation.recipient_id
  end

  def donation_params
    params.require(:donation).permit(
      :recipient_id, :recipient_type, :amount, :at_tip, :name, :anonymous, :message, :email, :at_newsletter, :family_email_updates, :hide_amount, :recurring, :stripe_token
    )
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
  # TODO make this accept scope: eg: global, family_id, etc.
  def global_donations
    Donation.pluck(:amount).sum
  end

  def pretty_dollars(value, decimals=0)
    decimal_amount = '%0.' + decimals.to_s + 'f'
    dollar_value = sprintf(decimal_amount, value)
    '$' + number_with_delimiter(dollar_value)
  end

  def cancel_url(recipient, donation)
    if donation.recipient_type == 'Family'
      family_donations_path(recipient) + '/cancel/' + donation.token
    else
      charity_donations_path(recipient) + '/cancel/' + donation.token
    end
  end
end

app/views/admin/donations/edit.html.haml
%h1
  .small.show #{link_to 'Admin', admin_donations_path} /
  Edit Donation to #{@recipient.full_name}
%p
  :markdown
    This is for changing **information**, it does _NOT_ actually change the credit card again. You can do refunds, extra charges, subscriptions, etc from #{stripe_url(@donation, 'this donation\'s Stripe Profile', 'Stripe URL')}.
= form_for([@recipient, @donation], html: { 'data-parsley-validate' => true, autocomplete: 'on' }) do |f|
  = render 'shared/errors', object: @donation
  %span.payment-errors
  %noscript
    %p FYI: This form requires Javascript to complete. If you don't have javascript enabled, you won't be able to donate :(
  %fieldset
    %legend
      Amount
    .form-group.donation-amount(data-toggle='buttons')
      - Donation::DONATION_AMOUNTS.each do |amount|
        = f.label :amount, value: amount, class: 'btn btn-default' do
          = f.radio_button :amount, amount
          = '$' + amount.to_s
      -# The empty quotes are to keep the label text empty
      = label_tag 'donation_amount_other', '' do
        = radio_button_tag 'donation[amount]', 'other', nil
        = telephone_field_tag 'other_text', nil, placeholder: 'Other amount', class: 'form-control'
        %p.small.help-block The average gift is #{pretty_dollars(average_donation_amount)}
    -# Tips for AT when you're already donating to AT is redundant, so let's hide it
    - if @donation.recipient_type != 'Charity'
      %p.radio-label AdoptTogether Tip
      .radio-group
        - Donation::TIP_AMOUNTS.each do |key, value|
          .radio
            = f.label :at_tip, value: key do
              = f.radio_button :at_tip, key
              #{value}
              %span.tip-amount
        .radio
          = label_tag 'donation_at_tip_other', nil do
            = radio_button_tag 'donation[at_tip]', 'other', nil
            Other |
            = telephone_field_tag 'tip_other_text', nil, placeholder: '$0', class: 'form-control'
    %p.small.help-block AdoptTogether is a non profit service for adoptive families. We are a 501(c)(3) non profit funded completely by people just like you who make these small donations.
    .checkbox
      = f.label :hide_amount, class: 'checkbox' do
        = f.check_box :hide_amount
        Make my donation amount private
  %fieldset
    %legend Enter your information
    .row
      .col-xs-12.col-md-6
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control', required: :true, 'data-parsley-trigger' => 'focusout change'
        .checkbox
          = f.label :anonymous, class: 'checkbox' do
            = f.check_box :anonymous
            Make this donation anonymous
    .row
      .col-xs-12
        .form-group
          - if @donation.recipient_type != 'Charity'
            = f.label :message, 'Message to the Family'
          -else
            = f.label :message, 'Message to the AdoptTogether Team'
          = f.text_area :message, size: '60x6', class: 'form-control'
          %p.small.help-block This message will be public.
    .row
      .col-xs-12.col-md-6
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control', type: :email, required: :true, 'data-parsley-trigger' => 'focusout change'
        .checkbox
          = f.label :recurring, class: 'checkbox' do
            = f.check_box :recurring
            Make this a monthly donation. Each month you will bring this family closer to their goal.
  .row
    .col-xs-12.col-md-6
      = f.submit 'Donate', class: 'btn btn-primary btn-block donation', data: { disable_with: 'Donating...' }

app/views/admin/donations/index.html.haml
%h1
  %span.show.small
    = link_to 'Admin', admin_path
    \ /
  All #{pluralize(@donations.total_count, 'Donation')}
  - if @family.present?
    for #{link_to @family.full_name, family_path(@family)}
.pull-right
  = link_to 'Export as CSV', admin_donations_path(format: 'csv'), class: 'btn btn-sm btn-default'
  = link_to 'Export as XLS', admin_donations_path(format: 'xls'), class: 'btn btn-sm btn-default'
= paginate(@donations)
%table.table.table-hover
  %thead
    %tr
      %th= sortable 'name', 'Donor Name'
      %th= sortable 'email'
      %th Recipient
      %th= sortable 'amount'
      %th= sortable 'at_tip'
      %th= sortable 'recurring', 'Monthly?'
      %th= sortable 'created_at', 'Date Donated'
      %th Stripe Link
      %th Actions
  %tbody
    - @donations.each do |donation|
      %tr
        %td
          %strong
            = donation.name
          - if donation.anonymous?
            %span.small (Anonymous)
        %td= donation.email
        %td= link_to donation.recipient.full_name, donation.recipient
        %td
          = pretty_dollars(donation.amount)
          - if donation.hide_amount?
            %span.small (hidden)
        %td= pretty_dollars(donation.at_tip)
        %td= donation.recurring?
        %td.small{title: donation.created_at.strftime("on %-m/%-d/%Y at %l:%M %p")} #{time_ago_in_words(donation.created_at)} ago
        %td= stripe_url(donation, '💳', 'Stripe Profile')
        %td= link_to '📝', edit_admin_donation_path(donation), title: 'Edit Donation'
= paginate(@donations)